config/routes.rb
Rails.application.routes.draw do

  resources :openbattles
  resources :multivotes
  resources :topics
  resources :streams do
    member do
      post :vote_for_left
      post :vote_for_right
      get :invitechallenge
    end
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'omniauth_callback'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'battles#index'

  get 'about' => 'battles#about'

  get 'contact' => 'battles#contact'

  resources :battles do
    member do
      post :follow_left_video
      post :unfollow_left_video
      post :follow_right_video
      post :unfollow_right_video
      post :vote_for_left
      post :vote_for_right
      get :congratulation
      get :challengepreviewleft
      get :challengepreviewright
      
    end

    # resources :videos do
    #   resources :video_comments, only: [:new, :create]
    # end
    resources :battle_comments, only: [:new, :create]
  end

  namespace :admin do
    resources :videos do
      #resources :video_comments
    end
    resources :t1topics do
    end
    resources :topics do 
    end

    resources :battles do
      member do
        post :publish
        post :hidden
      end
      resources :battle_comments
    end
    
    resources :streams do
      member do
        post :approve
        post :rollback
        get :append
        get :reorder
        post :appended
        post :reordered
        get :addvideo
        post :addvideodone
        get :editvideo
        post :editvideodone
        
      end
    end

    resources :users
  end
  namespace :myasset do
    resources :videos do
      get :challenge
      post :createchallenge
      #resources :video_comments
    end
    
    resources :t1topics do
    end
    
    resources :topics do
      post :createvideo
      get :newvideo
    end
    
    resources :battles do
      resources :battle_comments
      get :challenge_left
      get :challenge_right
      post :createChallenge_left
      post :createChallenge_right
      post :disable
      post :enable
    end

    #resources :users
  end

  namespace :api do
    namespace :v1 do
      
      get 'upyunauths' => 'upyunauths#index'
      get 'wxappauths' => 'wxappauths#index'
      post 'wxappuserupdate' => 'wxappauths#patchwxappuser'
      get 'wxappuserverify' => 'wxappauths#verifywxappuser'
      post 'addvideototopic' => 'openbattles#addvideototopic'
      get 'listallvideos' => 'videos#listallvideos'
      

      resources :openbattles do
      end
      
      resources :myvotes
      resources :streams
      resources :videos do
        member do
          post :new_ext_video
          post :video_convert_done
          post :thumb_done
        end
      end
      resources :battles do
        member do
          post :follow_left_video
          post :unfollow_left_video
          post :follow_right_video
          post :unfollow_right_video
        end

    # resources :videos do
    #   resources :video_comments, only: [:new, :create]
    # end
      resources :battle_comments, only: [:new, :create]
      end
    end
  end
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :title, presence: true
  validates :t1topic_id, presence: true
  validates :running, presence: true
  
    belongs_to :t1topic
    belongs_to :user
    has_many :topic_videos
    has_many :videos , through: :topic_videos
end

app/controllers/admin/topics_controller.rb
class Admin::TopicsController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_required
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
  layout "admin"

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to admin_topic_url(@topic), notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to admin_topic_url(@topic), notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to admin_topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :running, :order, :t1topic_id)
    end
end

app/controllers/myasset/topics_controller.rb
class Myasset::TopicsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics/1
  # GET /topics/1.json
  def show
      @videos = @topic.videos.where(:user => current_user)
  end


  def newvideo
    @topic = Topic.find(params[:topic_id])
      @video = Video.new
  end
  # POST /topics/1/createvideo
  
  def createvideo
      video_topic = Topic.find(params[:topic_id])
      @video = current_user.videos.new(video_params)
      if @video.save
          @topic_video = current_user.topic_videos.new(video: @video, topic: video_topic)
          if @topic_video.save
          else
          end
          redirect_to myasset_topic_path(video_topic), notice: '视频上传成功!'
      else
        render :new
      end
  end
  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)

    respond_to do |format|
      if @topic.save
        format.html { redirect_to admin_topic_url(@topic), notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :running, :order, :t1topic)
    end
    def video_params
      params.require(:video).permit(:title, :description, :video, :image)
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show]

  # GET /topics/1
  # GET /topics/1.json
  def show
      @title = @topic.title
      @videoindex = params[:cur_videoid].to_i
      allvideo = @topic.videos.all.reverse
      if @videoindex
        @currentvideo = allvideo[@videoindex]
        @nextvideo = allvideo[@videoindex + 1]
        if @videoindex != 0
          @prevideo = allvideo[@videoindex - 1]
        end
      else
        @videoindex = 0
        @currentvideo = allvideo[@videoindex]
        @nextvideo = allvideo[@videoindex + 1]
      end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :running, :order, :t1topic)
    end
    def video_params
      params.require(:video).permit(:title, :description, :video, :image)
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_footer.html.erb
<div class="row button-footer">
       	<div class="col-xs-4 text-center">
       	  <% if @prevideo %>
                <%= link_to topic_path(@topic, cur_videoid:(@videoindex - 1)), :data => {:trackevent => "prev_show"}  do %>
                        <i class= "fa fa-arrow-left fa-2x" aria-hidden="true"></i>
                <% end %>
          <% else %>
        	  <%= link_to("", "#") %>
          <% end %>

		</div>
       	<div class="col-xs-4 text-center">
                <%= link_to myasset_topic_newvideo_path(@topic), :data => {:trackevent => "create_video_topic"} do %>
                            <i class= "fa fa-video-camera fa-2x" aria-hidden="true"></i>
                <% end %>
		</div>
       	<div class="col-xs-4 text-center">
       	    <% if @nextvideo %>
                <%= link_to topic_path(@topic, cur_videoid:(@videoindex + 1)), :data => {:trackevent => "next_video_topic"}  do %>
                        <i class= "fa fa-arrow-right fa-2x" aria-hidden="true"></i>
                <% end %>
            <% else %>
        	    <%= link_to("", "#") %>
        	<% end %>
       	</div>
</div>

app/views/topics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Topics</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Title</th>
      <th>Running</th>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.t1topic.title %></td>
        <td><%= topic.title %></td>
        <td><%= topic.running %></td>
        <td><%= topic.order %></td>
        <td><%= link_to 'Show', admin_topic_path(topic) %></td>
        <td><%= link_to 'Edit', edit_admin_topic_path(topic) %></td>
        <td><%= link_to 'Destroy', admin_topic_path(topic), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Topic', new_admin_topic_path %>

app/views/topics/show.html.erb
<div class="container-fluid">
<div class="row">
    <%= link_to "回到" + @topic.t1topic.title, openbattle_path(@topic.t1topic) %>
  </div>
  <div class="row text-center">
     <h4>话题：<%= @topic.title %></h4>
  </div>
</div>

<% if @currentvideo %>
  <div class="row col-sm-12 col-xs-12">
       <%= @currentvideo.user.name %>: <%= @currentvideo.title %>
  </div>
  
  <div class="row col-sm-12 col-xs-12 video_container">
    <% if @currentvideo %>
      <%= render :partial => "common/video_player", locals: {video: @currentvideo}%>
    <% end %>
  </div>
    <span></span>
    <div class="row col-sm-12 col-xs-12 text-center challenge_in_topic">
              <%= link_to("怼TA", myasset_video_challenge_path(@currentvideo), :class => "btn btn-primary btn-challenge") %>
    </div>
<% else %>
    <div class="row col-xs-12 text-center">
                <%= link_to myasset_topic_newvideo_path(@topic), :data => {:trackevent => "create_video_topic"} do %>
                           等你来说 <i class= "fa fa-video-camera fa-2x" aria-hidden="true"></i>
                <% end %>
		</div>
<% end %>
<%= render "footer" %>
</div>