config/routes.rb
Rails.application.routes.draw do

  resources :openbattles
  resources :multivotes
  resources :topics
  resources :streams do
    member do
      post :vote_for_left
      post :vote_for_right
      get :invitechallenge
    end
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'omniauth_callback'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'battles#index'

  get 'about' => 'battles#about'

  get 'contact' => 'battles#contact'

  resources :battles do
    member do
      post :follow_left_video
      post :unfollow_left_video
      post :follow_right_video
      post :unfollow_right_video
      post :vote_for_left
      post :vote_for_right
      get :congratulation
      get :challengepreviewleft
      get :challengepreviewright
      
    end

    # resources :videos do
    #   resources :video_comments, only: [:new, :create]
    # end
    resources :battle_comments, only: [:new, :create]
  end

  namespace :admin do
    resources :videos do
      #resources :video_comments
    end
    resources :t1topics do
    end
    resources :topics do 
    end

    resources :battles do
      member do
        post :publish
        post :hidden
      end
      resources :battle_comments
    end
    
    resources :streams do
      member do
        post :approve
        post :rollback
        get :append
        get :reorder
        post :appended
        post :reordered
        get :addvideo
        post :addvideodone
        get :editvideo
        post :editvideodone
        
      end
    end

    resources :users
  end
  namespace :myasset do
    resources :videos do
      get :challenge
      post :createchallenge
      #resources :video_comments
    end
    
    resources :t1topics do
    end
    
    resources :topics do
      post :createvideo
      get :newvideo
    end
    
    resources :battles do
      resources :battle_comments
      get :challenge_left
      get :challenge_right
      post :createChallenge_left
      post :createChallenge_right
      post :disable
      post :enable
    end

    #resources :users
  end

  namespace :api do
    namespace :v1 do
      
      get 'upyunauths' => 'upyunauths#index'
      get 'wxappauths' => 'wxappauths#index'
      post 'wxappuserupdate' => 'wxappauths#patchwxappuser'
      get 'wxappuserverify' => 'wxappauths#verifywxappuser'
      post 'addvideototopic' => 'openbattles#addvideototopic'
      get 'listallvideos' => 'videos#listallvideos'
      

      resources :openbattles do
      end
      
      resources :myvotes
      resources :streams
      resources :videos do
        member do
          post :new_ext_video
          post :video_convert_done
          post :thumb_done
        end
      end
      resources :battles do
        member do
          post :follow_left_video
          post :unfollow_left_video
          post :follow_right_video
          post :unfollow_right_video
        end

    # resources :videos do
    #   resources :video_comments, only: [:new, :create]
    # end
      resources :battle_comments, only: [:new, :create]
      end
    end
  end
end

app/models/stream.rb
class Stream < ApplicationRecord
  belongs_to :user
  has_many :multivotes
  has_many :inside_battles, through: :multivotes, source: :battle
  has_many :challengevideos
  has_many :inside_videos, through: :challengevideos, source: :video
end

app/controllers/admin/streams_controller.rb
class Admin::StreamsController < ApplicationController
  before_action :set_stream, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :admin_required

  layout "admin"

  # GET /streams
  # GET /streams.json
  def index
    @streams_waiting_prove  = Stream.all.where(approved: false)
    @streams_proved  = Stream.all.where(approved: true)

  end

  # GET /streams/1
  # GET /streams/1.json
  def show
    @challenge_video = @stream.inside_videos.first
  end
  # GET /streams/1/edit
  def edit
  end
  
  # GET /stream/1/addvideo
  def addvideo
    @stream = Stream.find(params["id"])
    @videos = Video.all.map { |v| [v.title, v.id] }
  end
  def addvideodone
    @stream = Stream.find(params["id"])
    video = Video.find(params["video"])
    challengevideo = Challengevideo.new
    challengevideo.user = current_user
    challengevideo.stream = @stream
    challengevideo.video = video
    if challengevideo.save
      redirect_to admin_stream_url(@stream)
    else
      redirect_to admin_streams_url
    end
  end
  
  def editvideo
    @stream = Stream.find(params["id"])
    @videos = Video.all.map { |v| [v.title, v.id] }
  end
  def editvideodone
    @stream = Stream.find(params["id"])
    video_id = params["video"]
    challenge_video = @stream.challengevideos.first
    if params["commit"] == "删除"
      @stream.challengevideos.first.delete
    else
      challenge_video.video = Video.find(video_id)
      challenge_video.save
    end
    redirect_to admin_stream_url(@stream)
  end
  # GET /streams/1/append
  def append
    @stream = Stream.find(params["id"])
    battles_in_stream = @stream.inside_battles.all
    battles_all = current_user.battles.all
    battles_not_in_stream = battles_all.select do |battle|
      battles_in_stream.exclude? battle
    end
    @battles = battles_not_in_stream.map { |v| [v.title, v.id] }
  end
  # POST /streams/1/appended
  def appended
    @stream = Stream.find(params["id"])
    @battle = Battle.find(params["battle"])
    order = params["order"]
    @multivote = Multivote.new
    @multivote.stream = @stream
    @multivote.battle = @battle
    @multivote.order = order
    if @multivote.save
      redirect_to admin_stream_url(@stream)
    else
      redirect_to admin_streams_url
    end
  end

  # GET /streams/1/reordered
  def reorder
    @stream = Stream.find(params["id"])
  end
  # POST /streams/1/reordered
  def reordered
    
    @stream = Stream.find(params["id"])
    order = params["order"]
    if params["commit"] == "删除"
      multivote = @stream.multivotes.find_by(:battle_id => params["battle"])
      multivote.delete
      if @stream.multivotes.all.count > 0
        redirect_to admin_stream_url(@stream)
      else
        redirect_to admin_streams_url
      end
    else
      multivote = @stream.multivotes.find_by(:battle_id => params["battle"])
      multivote.order = order
      multivote.save
      redirect_to admin_stream_url(@stream)
    end
  end

  # POST /streams
  # POST /streams.json
  def create
    @stream = current_user.streams.new(stream_params)
    @stream.approved = false
    @stream.running = true
    

    respond_to do |format|
      if @stream.save
        format.html { redirect_to admin_stream_url(@stream), notice: 'Stream was successfully created.' }
        format.json { render :show, status: :created, location: @stream }
      else
        format.html { render :new }
        format.json { render json: @stream.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /streams/1
  # PATCH/PUT /streams/1.json
  def update
    respond_to do |format|
      if @stream.update(stream_params)
        format.html { redirect_to admin_streams_url, notice: 'Stream was successfully updated.' }
        format.json { render :show, status: :ok, location: @stream }
      else
        format.html { render :edit }
        format.json { render json: @stream.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /streams/1
  # DELETE /streams/1.json
  def destroy
    @stream.destroy
    respond_to do |format|
      format.html { redirect_to admin_streams_url, notice: 'Stream was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def approve
    @stream = Stream.find(params[:id])
    @stream.approved = true
    @stream.save
    redirect_to :back
  end

  def rollback
    @stream = Stream.find(params[:id])
    @stream.approved = false
    @stream.save
    redirect_to :back
  end

  # GET /streams/new
  def new
    @stream = Stream.new
  end

  # GET /streams/1/edit
  def edit
  end




  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stream
      @stream = Stream.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stream_params
      params.require(:stream).permit(:title, :content, :approved, :running)
    end
end

app/controllers/api/v1/streams_controller.rb
class Api::V1::StreamsController < ApplicationController
  skip_before_action :verify_authenticity_token, if: :json_request?
  before_action :set_stream, only: [:show, :vote_for_left, :vote_for_right, :invitechallenge]

  def json_request?
    request.format.json?
  end

  def index
    @streams = Stream.all
  end
  # GET /streams/1
  # GET /streams/1.json
  def show
      if !@stream.approved or !@stream.running
        render status: :no_content
      else
        battle_order = @stream.multivotes.all.sort_by{|bo| bo.order}
        available_battle = battle_order.select do |each| 
          !is_voted(Battle.find(each.battle_id))
        end
        @battles_in_stream = available_battle.map {|v| 
         b = Battle.find(v.battle_id)
         lvideo = Video.find(b.left_video_id)
         rvideo = Video.find(b.right_video_id)
         
         {:battle_id => b.id, :left_video_url => lvideo.video_url.to_s, :left_video_poster => lvideo.image.thumb.to_s,:right_video_url => rvideo.video_url.to_s, :right_video_poster => rvideo.image.thumb.to_s}
        }
      end
  end

  def invitechallenge
      if !@stream.approved or !@stream.running
        redirect_to root_url
      end
      @video = @stream.inside_videos.first
  end


  # GET /streams/new
  def new
    @stream = Stream.new
  end
  def vote_for_left
    @remainBattles = remain_battles_in_stream(@stream)
    @battle = @remainBattles.first
    battle = Battle.find(params["battle"])
    if current_user
      current_user.follow_left!(battle)
      flash[:warning] = "投票成功" if request.format.html?
      if @battle
        respond_to do |format|
          format.html {redirect_to :back}
          format.js
        end
      else
        if @stream.inside_videos.first
          redirect_to invitechallenge_stream_url(@stream)
        else
          redirect_to root_url
        end
      end
    else
      #visitor click left vote button
      visitorID = find_visitor_id
      newVote = battle.visitor_votes.build(visitorID:visitorID,voteLeft:true)
      flash[:warning] = "投票成功" if request.format.html?
      newVote.save
      if @battle
        respond_to do |format|
          format.html {redirect_to :back}
          format.js
        end
      else
        if @stream.inside_videos.first
          redirect_to invitechallenge_stream_url(@stream)
        else
          redirect_to root_url
        end
      end
    end
  end
  
  def vote_for_right
    @remainBattles = remain_battles_in_stream(@stream)
    @battle = @remainBattles.first
    battle = Battle.find(params["battle"])
    if current_user
      current_user.follow_right!(battle)
      if @battle
      flash[:warning] = "投票成功" if request.format.html?
        respond_to do |format|
          format.html {redirect_to :back}
          format.js
        end
      else
        if @stream.inside_videos.first
          redirect_to invitechallenge_stream_url(@stream)
        else
          redirect_to root_url
        end
      end
    else
      #visitor click left vote button
      visitorID = find_visitor_id
      newVote = battle.visitor_votes.build(visitorID:visitorID,voteLeft:false)
      newVote.save
      if @battle      
        flash[:warning] = "投票成功" if request.format.html?
        respond_to do |format|
          format.html {redirect_to :back}
          format.js
        end
      else
        if @stream.inside_videos.first
          redirect_to invitechallenge_stream_url(@stream)
        else
          redirect_to root_url
        end
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stream
      @stream = Stream.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stream_params
      params.require(:stream).permit(:title, :content)
    end
  def find_visitor_id
    visitorID = ""
    if(visitor_id_incookie = cookies.signed[:doudouapp_vd])
      visitorID = visitor_id_incookie
    else
      visitorID = Time.now.to_s
      cookies.permanent.signed[:doudouapp_vd] = visitorID
    end
    visitorID
  end
  def right_is_voted(battle)
    if current_user
      current_user.has_follow_right?(battle)
    else
      visitorID = find_visitor_id
      battle.visitor_votes.find_by(visitorID:visitorID, voteLeft:false) != nil
    end
  end  
  def left_is_voted(battle)
    if current_user
      current_user.has_follow_left?(battle)
    else
      visitorID = find_visitor_id
      battle.visitor_votes.find_by(visitorID:visitorID, voteLeft:true) != nil
    end
  end
  def is_voted(battle)
    left_is_voted(battle) or right_is_voted(battle)
  end
  def remain_battles_in_stream(stream)
      battles_in_stream_inorder = stream.multivotes.all.sort_by{|bo| bo.order}
      remainbattles_in_stream_inorder = battles_in_stream_inorder.select do |battle_order|
        "#{battle_order.battle_id}" != params["battle"] and !is_voted(Battle.find(battle_order.battle_id))
      end
      remainbattles_in_stream_inorder.map {|v| Battle.find(v.battle_id)}
  end
    def verify_api_only
        Thirdapp.where(:appid => params[:appid], :secret => params[:appsecret]).count > 0
    end

end

app/controllers/myasset/streams_controller.rb
class Myasset::StreamsController < ApplicationController
  before_action :set_stream, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  layout "myasset"
  # GET /streams
  # GET /streams.json
  def index
    @streams = current_user.streams.all
  end

  # GET /streams/1
  # GET /streams/1.json
  def show
  end

  # GET /streams/new
  def new
    @stream = Stream.new
  end

  # GET /streams/1/edit
  def edit
  end

  # GET /streams/1/append
  def append
    @stream = Stream.find(params["stream_id"])
    battles_in_stream = @stream.inside_battles.all
    battles_all = current_user.battles.all
    battles_not_in_stream = battles_all.select do |battle|
      battles_in_stream.exclude? battle
    end
    @battles = battles_not_in_stream.map { |v| [v.title, v.id] }
  end
  # POST /streams/1/appended
  def appended
    @stream = Stream.find(params["stream_id"])
    @battle = Battle.find(params["battle"])
    order = params["order"]
    @multivote = Multivote.new
    @multivote.stream = @stream
    @multivote.battle = @battle
    @multivote.order = order
    if @multivote.save
      redirect_to myasset_stream_url(@stream)
    else
      redirect_to myasset_streams_url
    end
  end

  # GET /streams/1/reordered
  def reorder
    @stream = Stream.find(params["stream_id"])
  end
  # POST /streams/1/reordered
  def reordered
    
    @stream = Stream.find(params["stream_id"])
    order = params["order"]
    if params["commit"] == "删除"
      multivote = @stream.multivotes.find_by(:battle_id => params["battle"])
      multivote.delete
      if @stream.multivotes.all.count > 0
        redirect_to myasset_stream_url(@stream)
      else
        redirect_to myasset_streams_url
      end
    else
      multivote = @stream.multivotes.find_by(:battle_id => params["battle"])
      multivote.order = order
      multivote.save
      redirect_to myasset_stream_url(@stream)
    end
  end

  # POST /streams
  # POST /streams.json
  def create
    @stream = current_user.streams.new(stream_params)
    @stream.approved = false
    @stream.running = true
    

    respond_to do |format|
      if @stream.save
        format.html { redirect_to myasset_stream_url(@stream), notice: 'Stream was successfully created.' }
        format.json { render :show, status: :created, location: @stream }
      else
        format.html { render :new }
        format.json { render json: @stream.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /streams/1
  # PATCH/PUT /streams/1.json
  def update
    respond_to do |format|
      if @stream.update(stream_params)
        format.html { redirect_to myasset_stream_url(@stream), notice: 'Stream was successfully updated.' }
        format.json { render :show, status: :ok, location: @stream }
      else
        format.html { render :edit }
        format.json { render json: @stream.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /streams/1
  # DELETE /streams/1.json
  def destroy
    @stream.destroy
    respond_to do |format|
      format.html { redirect_to myasset_streams_url, notice: 'Stream was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stream
      @stream = Stream.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stream_params
      params.require(:stream).permit(:title, :content)
    end
end

app/helpers/streams_helper.rb
module StreamsHelper
  def right_is_voted(battle)
    if current_user
      current_user.has_follow_right?(battle)
    else
      visitorID = find_visitor_id
      battle.visitor_votes.find_by(visitorID:visitorID, voteLeft:false) != nil
    end
  end  
  def left_is_voted(battle)
    if current_user
      current_user.has_follow_left?(battle)
    else
      visitorID = find_visitor_id
      battle.visitor_votes.find_by(visitorID:visitorID, voteLeft:true) != nil
    end
  end
  def is_voted(battle)
    left_is_voted(battle) or right_is_voted(battle)
  end
end

app/views/streams/_battleinstream.html.erb
  <% battle = local_assigns[:battle] %>
      <div class="row">
      
        <div class="col-xs-12" style="text-align:center">
            <div class="panel1">
              <h4 ><%= battle.title %></h4>
            </div>
        </div>
      </div>
      <%= render :partial => "common/video_battle", locals: {battle: battle}%>
      <div id="<%= "votebar_battle_#{battle.id}"%>">
      <%= render :partial => "votebar_battle", locals: {battle: battle}%>
      </div>

app/views/streams/_leftvotebutton.html.erb
  <% battle = local_assigns[:battle] %>
     <% if left_is_voted(battle) %>
         <%  left_vote_link_text = "fa fa-heart fa-2x"%>
     <% else %>
         <%  left_vote_link_text = "fa fa-heart-o fa-2x"%>
     <% end %>
     <% if left_is_voted(battle)%>
        <i class= "<%= "#{left_vote_link_text}"%>" aria-hidden="true" style="color:#00314f;"></i>

    <% elsif !right_is_voted(battle)%>
                <%= link_to vote_for_left_stream_path(@stream, :battle => battle.id), :method => :post,
                                               :remote => @remainBattles.count > 0 do %>
                        <i class= "<%= "#{left_vote_link_text}"%>" aria-hidden="true" style="color:#00314f;"></i>
                <% end %>    
    <% end %>

app/views/streams/_rightvotebutton.html.erb
  <% battle = local_assigns[:battle] %>
     <% if right_is_voted(battle) %>
         <%  right_vote_link_text = "fa fa-heart fa-2x flip"%>
     <% else %>
         <%  right_vote_link_text = "fa fa-heart-o fa-2x flip"%>
     <% end %>
     
    <%if right_is_voted(battle)%>
                        <i class= "<%= "#{right_vote_link_text}"%>" aria-hidden="true" style="color:#d71a21;"></i>
                
    <% elsif  !left_is_voted(battle)%>
                <%= link_to vote_for_right_stream_path(@stream, :battle => battle.id), :method => :post,
                                               :remote => @remainBattles.count > 1 do %>
                        <i class= "<%= "#{right_vote_link_text}"%>" aria-hidden="true" style="color:#d71a21;"></i>
                <% end %>
    <% end %>

app/views/streams/_votebar_battle.html.erb
  <% battle = local_assigns[:battle] %>

  <% if battle %>
  <div class="row">
    <div class="col-sm-2 col-xs-2">
        <%= render :partial => "leftvotebutton", locals: {battle: battle}%>     
    </div>
    <div class = "col-sm-8 col-xs-8">
        <%= render :partial => "common/votebar", locals: {battle: battle}%>
    </div>
    <div class="col-sm-2 col-xs-2" style="text-align:right">
        <%= render :partial => "rightvotebutton", locals: {battle: battle}%>     
    </div>
    </div>
  <% end %>

app/views/streams/invitechallenge.html.erb
<p id="notice"><%= notice %></p>
<div class="row col-xs-12 col-sm-12">
        <div class="panel1">
            <h4 align="center">  <%= @video.title %></h4>
            <!-- <p class="pull-left" style="margin-left: 10px; height: 30px;"><%#= simple_format(battle.description) %></p> -->
        </div>
</div>
<div class="row col-xs-12 col-sm-12">
        <div class="panel1">
            <p align="center"><%= @video.description %></p>
            <!-- <p class="pull-left" style="margin-left: 10px; height: 30px;"><%#= simple_format(battle.description) %></p> -->
        </div>
</div>
<div>
    <div class="col-xs-12 col-sm-12">
      <video src=<%= @video.video_url.to_s %> style = "width:100%"  poster=<%= @video.image.thumb.to_s %> controls>
        <p>Your browser doesn't support HTML5 video. Here is a <a href="rabbit320.webm">link to the video</a> instead.</p>
      </video>
    </div>
</div>

    <div class="col-sm-12 col-xs-12 text-center">
              <%= link_to("怼TA", myasset_video_challenge_url(@video), :class => "btn btn-default challenge_left") %>
    </div>
    
    
    <br>
    
    <% if @streams and @streams.inside_battles.count > 0 %>
        <div class="rwow col-xs-12 col-sm-12" style="text-align:center">
              <h4 >您已经投了: <%=  @stream.title %></h4>
        </div>
            <% @stream.inside_battles.each do |b| %>
              <%= render :partial => "common/video_battle", locals: {battle: b}%>
              <%= render :partial => "common/votebar_battle", locals: {battle: b}%>
            <% end %>
    <% end %>

app/views/streams/show.html.erb
<p id="notice"><%= notice %></p>
  <% if @battle %>
    <div class="container" id="<%= "singlebattleinstream"%>">

      <div class="row">
      
        <div class="col-xs-12" style="text-align:center">
            <div class="panel1">
              <h4 ><%= @battle.title %></h4>
            </div>
        </div>
      </div>
      <%= render :partial => "common/video_battle", locals: {battle: @battle}%>
      <%= render :partial => "votebar_battle", locals: {battle: @battle}%>
    </div>
  <% else %>
        <div class="col-xs-12" style="text-align:center">
            <div class="panel1">
              <h4 ><%= @stream.title %></h4>
            </div>
        </div>
    <% @stream.inside_battles.each do |b| %>
      <%= render :partial => "common/video_battle", locals: {battle: b}%>
      <%= render :partial => "common/votebar_battle", locals: {battle: b}%>
    <% end %>
  
  <% end %>

app/views/streams/vote_for_left.js.erb
$("#singlebattleinstream").html('<%= escape_javascript("#{render :partial => "battleinstream", locals: {battle: @battle}}").html_safe %>');

app/views/streams/vote_for_right.js.erb
$("#singlebattleinstream").html('<%= escape_javascript("#{render :partial => "battleinstream", locals: {battle: @battle}}").html_safe %>');