config/routes.rb
Rails.application.routes.draw do

  resources :openbattles
  resources :multivotes
  resources :topics
  resources :streams do
    member do
      post :vote_for_left
      post :vote_for_right
      get :invitechallenge
    end
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'omniauth_callback'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'battles#index'

  get 'about' => 'battles#about'

  get 'contact' => 'battles#contact'

  resources :battles do
    member do
      post :follow_left_video
      post :unfollow_left_video
      post :follow_right_video
      post :unfollow_right_video
      post :vote_for_left
      post :vote_for_right
      get :congratulation
      get :challengepreviewleft
      get :challengepreviewright
      
    end

    # resources :videos do
    #   resources :video_comments, only: [:new, :create]
    # end
    resources :battle_comments, only: [:new, :create]
  end

  namespace :admin do
    resources :videos do
      #resources :video_comments
    end
    resources :t1topics do
    end
    resources :topics do 
    end

    resources :battles do
      member do
        post :publish
        post :hidden
      end
      resources :battle_comments
    end
    
    resources :streams do
      member do
        post :approve
        post :rollback
        get :append
        get :reorder
        post :appended
        post :reordered
        get :addvideo
        post :addvideodone
        get :editvideo
        post :editvideodone
        
      end
    end

    resources :users
  end
  namespace :myasset do
    resources :videos do
      get :challenge
      post :createchallenge
      #resources :video_comments
    end
    
    resources :t1topics do
    end
    
    resources :topics do
      post :createvideo
      get :newvideo
    end
    
    resources :battles do
      resources :battle_comments
      get :challenge_left
      get :challenge_right
      post :createChallenge_left
      post :createChallenge_right
      post :disable
      post :enable
    end

    #resources :users
  end

  namespace :api do
    namespace :v1 do
      
      get 'upyunauths' => 'upyunauths#index'
      get 'wxappauths' => 'wxappauths#index'
      post 'wxappuserupdate' => 'wxappauths#patchwxappuser'
      get 'wxappuserverify' => 'wxappauths#verifywxappuser'
      post 'addvideototopic' => 'openbattles#addvideototopic'
      get 'listallvideos' => 'videos#listallvideos'
      

      resources :openbattles do
      end
      
      resources :myvotes
      resources :streams
      resources :videos do
        member do
          post :new_ext_video
          post :video_convert_done
          post :thumb_done
        end
      end
      resources :battles do
        member do
          post :follow_left_video
          post :unfollow_left_video
          post :follow_right_video
          post :unfollow_right_video
        end

    # resources :videos do
    #   resources :video_comments, only: [:new, :create]
    # end
      resources :battle_comments, only: [:new, :create]
      end
    end
  end
end

app/views/common/_bar_battle.html.erb
  <% battle = local_assigns[:battle] %>
  <% if battle %>
  <div class="row">
    <div class="col-sm-2 col-xs-2">
    </div>
    <div class = "col-sm-8 col-xs-8">
        <% if total_votes(battle) >0 %>
            <div class="progress" style="margin-top: 20px;">
                <div id="leftBar" class="progress-bar" role="progressbar" style="width:<%= render_left_width(battle)%>%;
                        background-color:#00314f; color:black;">
          
                    <p><%= left_votes(battle) %></p>
                </div>
                <div id="rightBar" class="progress-bar" role="progressbar" style="width:<%= render_right_width(battle)%>%;
                            background-color:#d71a21; color:white;" >
                    <p><%= right_votes(battle) %></p>
                </div>

            </div>
        <% else %>
            <div class="progress" style="margin-top: 20px;">
                <div id="leftBar" class="progress-bar" role="progressbar" style="width:100%; background-color:#efefef;">
                </div>
              </div>
        <% end %>
    </div>
    </div>
  <% end %>

app/views/common/_battleinstream.html.erb
  <% b = local_assigns[:stream] %>
    <div>
        <% b.multivotes.each do |relation| %>
            <div class="row">
              <div class= "col-xs-3">
                <%= relation.order%>
              </div>
            </div>
            <%= render :partial => "common/singlebattle", locals: {battle: relation.battle}%>
        <% end %>
    </div>

app/views/common/_challenge_battle.html.erb
  <% battle = local_assigns[:battle] %>
          <% if is_my_battle(battle) %>
          <% else %>
            <% if left_is_voted(battle) %>
                 <div class="row">

                      <div class="col-sm-12 col-xs-12 text-center">
                        <%= link_to("怼右边", myasset_video_challenge_url(battle.right_video), :class => "btn btn-default challenge_right") %>
                      </div>
                </div>
            <% elsif right_is_voted(battle) %>
                <div class="row">
                  <div class="col-sm-12 col-xs-12 text-center">
                    <%= link_to("怼左边", myasset_video_challenge_url(battle.left_video), :class => "btn btn-default challenge_left") %>
                  </div>  
                </div>
            <% end %>

           <% end %>

app/views/common/_comments_for_battle.html.erb
<% battle = local_assigns[:battle] %>
<div class="row comments">
  <div class="col-xs-12 ">
    <div class="comments-title">
      精选留言
      <span class="pull-right">
        <%= link_to new_battle_battle_comment_path(battle) do %>
          写评论 <i class="fa fa-pencil" aria-hidden="true"></i>
        <% end %>
      </span>
    </div>
    <br><br>
    <% if battle.battle_comments.blank? %>
      还没有人评论 ~
    <% else %>
      	<% @battle.battle_comments.order("created_at DESC").each do |comment| %>
	      <div class="row comment-list">
	        <div class="col-xs-2">
	          <div class="thumbnail1" style="margin-top:5px;">
	            <% if comment.user.avatar_url %>
	            <%#= image_tag(comment.user.avatar.url(:thumb), :size => "30x30", class: "img-circle") %>
	              <%= image_tag(comment.user.avatar_file_name.url(:thumb), :size => "30x30", class: "img-circle") %>
	            <% else %>
	            <%#= image_tag("http://placehold.it/100x100&text=No Pic", :size => "30x30", class: "img-circle") %>
	              <%= image_tag "logo.jpeg", :size => "30x30", class: "img-circle" %>
	            <% end %>
	          </div>
	        </div>
	        <div class="col-xs-10">
	          <p>
	            <% if comment.user.name.present? %>
	              <%= comment.user.name %>
	            <% else %>
	              <%= comment.user.display_name %>
	            <% end %>
	          </p>
	          <p>
	            <%= simple_format(comment.comment) %>
	          </p>
	          <p>
	            <%= comment.created_at.strftime("%Y年%-m月%d日") %>
	          </p>
	        </div>
	      </div>
		 <% end %>
    <% end %>
</div>
</div>

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container">
  <div class="row">
     <p class="text-center">Copyright ©2017 斗斗 All Rights Reserved
    </p>
</div>
  <div class="row">
   <p class="text-center">京ICP备17027685
    </p>
    </div>
</footer>

app/views/common/_footer_battle.html.erb
  <% battle = local_assigns[:battle] %>

<div class="row button-footer">
    <% if left_is_voted(battle) or right_is_voted(battle) %>
       	<div class="col-xs-4 text-center">
       	  <% if battle.newerpublishedbattle %>
                <%= link_to battle_path(battle.newerpublishedbattle) do %>
                        <i class= "fa fa-arrow-left" aria-hidden="true"></i>
                <% end %>
        	<% else %>
        	  <%= link_to("", "#") %>
        	<% end %>

		    </div>
       	<div class="col-xs-4 text-center">
            <% if left_is_voted(battle) %>
                <%= link_to myasset_video_challenge_url(battle.left_video) do %>
                            <i class= "fa fa-video-camera" aria-hidden="true"></i>我也怼右边
                <% end %>
            <% else %>
                <%= link_to myasset_video_challenge_url(battle.left_video) do %>
                            <i class= "fa fa-video-camera" aria-hidden="true"></i>我也怼左边
                <% end %>
            <% end %>
		    </div>
       	<div class="col-xs-4 text-center">
       	  <% if battle.olderpublishedbattle %>
                <%= link_to battle_path(battle.olderpublishedbattle) do %>
                        <i class= "fa fa-arrow-right" aria-hidden="true"></i>
                <% end %>
        	<% else %>
        	  <%= link_to("主人可以休息了", "#") %>
        	<% end %>
       	</div>
    <% else %>
       	<div class="col-xs-6 text-center">
       	  <% if battle.newerpublishedbattle %>
                <%= link_to battle_path(battle.newerpublishedbattle) do %>
                        <i class= "fa fa-arrow-left" aria-hidden="true"></i>
                <% end %>
        	<% else %>
        	  <%= link_to("", "#") %>
        	<% end %>

		    </div>
       	<div class="col-xs-6 text-center">
       	  <% if battle.olderpublishedbattle %>
                <%= link_to battle_path(battle.olderpublishedbattle) do %>
                        <i class= "fa fa-arrow-right" aria-hidden="true"></i>
                <% end %>
        	<% else %>
        	  <%= link_to("主人可以休息了", "#") %>
        	<% end %>
       	</div>
       	<% end %>
</div>

app/views/common/_leftvotebutton.html.erb
  <% battle = local_assigns[:battle] %>
  <% remote = local_assigns[:remote]%>
  <% needRemote = true %>
  <% if remote != nil and remote == false%>
    <% needRemote = false %>
  <% end %>
     <% if left_is_voted(battle) %>
         <%  left_vote_link_text = "fa fa-heart fa-2x"%>
     <% else %>
         <%  left_vote_link_text = "fa fa-heart-o fa-2x"%>
     <% end %>
     
     <% if left_is_voted(battle)%>
        <i class= "<%= "#{left_vote_link_text}"%>" aria-hidden="true" style="color:#135392;"></i>

    <% elsif !right_is_voted(battle)%>
                <%= link_to vote_for_left_battle_path(battle), :method => :post,
                                               :remote => needRemote, :track => true, :data => {:trackevent => "vote"} do %>
                        <i class= "<%= "#{left_vote_link_text}"%>" aria-hidden="true" style="color:#135392;"></i>
                <% end %>
    <% end %>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">

      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
       <a class="navbar-brand" href="/" data-trackevent="back_home_from_nav">
            <i class="fa fa-video-camera" aria-hidden="true"></i> 斗斗
            <%#= link_to("斗斗", root_path) %>
       </a>
        <span class="icon-bar"></span>
       <a class="navbar-brand" href="/openbattles" data-trackevent="back_home_from_nav">
            |  广场
            <%#= link_to("斗斗", root_path) %>
       </a>
    </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to("联系我们", contact_path, data:{trackevent: "contact_us_from_nav"}) %></li>
            <li><%= link_to("关于我们", about_path, data:{trackevent: "about_us_from_nav"}) %></li>

            <% if !current_user %>
                <li><%= link_to("注册", new_user_registration_path, data:{trackevent: "register_from_nav"}) %>
                </li>
                <li><%= link_to("登录", new_user_session_path, data:{trackevent: "login_from_nav"}) %></li>
            <% else %>
                <!-- <li class="round-image-50"><%#= image_tag(current_user.avatar.url(:thumb)) %></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <b class="caret"></b>
                    </a> -->
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                       <i class="fa fa-user" aria-hidden="true"></i>
                       <% if current_user.name.present? %>
                         <%= current_user.name %>
                      <% else %>
                        <%= current_user.email %>
                      <% end %>
                      <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <% if current_user.admin? %>
                        <li><%= link_to("管理员选单", admin_videos_path) %></li>
                        <% end %>
                        <li><%= link_to("我的视频和PK选单", myasset_videos_path) %></li>
                        <li><%= link_to '修改个人资料',edit_user_registration_path %></li>
                        <li><%= link_to("退出", destroy_user_session_path, method: :delete) %></li>
                    </ul>
            </ul>
        </li>
        <% end %>
    </ul>
</div>
<!-- /.navbar-collapse -->
</nav>

app/views/common/_singlebattleinmanager.html.erb
<% battle = local_assigns[:battle] %>
<div class="container" id="<%= "singlebattle_#{battle.id}"%>">

  <div id="<%= "votebar_battle_#{battle.id}"%>">
    <div class="row">
      <div class="col-xs-4 text-center left_user"><h3><%= @battle.left_video.user.name || "朝阳群众" %></h3></div>
      <div class="col-xs-4 text-center"><h3>VS</h3></div>
      <div class="col-xs-4 text-center right_user"><h3><%= @battle.right_video.user.name  || "朝阳群众" %></h3></div>
    </div>
    <div class="row text-center">
      <%= @battle.title %>
    </div>
    <%= render :partial => "common/bar_battle", locals: {battle: battle}%>
  </div>
    <%= render :partial => "common/video_battle", locals: {battle: battle}%>
</div>

app/views/common/_video_battle.html.erb
<% battle = local_assigns[:battle] %>
<% leftvideoautoplay = local_assigns[:leftvideoautoplay]%>
  <% needautoplayleftvideo = (leftvideoautoplay == true) %>
  <div class="row ">
    <div class="col-sm-6 col-xs-6 video_container">
     		<%= render :partial => "common/video_player", locals: {video: battle.left_video}%>
    </div>
    <div class="col-sm-6 col-xs-6 video_container">
     		<%= render :partial => "common/video_player", locals: {video: battle.right_video}%>
    </div>
  </div>

app/views/common/_video_player.html.erb
<% video = local_assigns[:video] %>
<% videoautoplay = local_assigns[:autoplay]%>
<% needautoplayvideo = (videoautoplay == true) %>
<% needautoplayvideo = false %>
<% posturl = video.poster_url %>
      <% if posturl  and posturl != "" %>
        <% if needautoplayvideo %>
		    <video src="<%= video.unique_url %>" style="width:100%" poster= <%= posturl %> autoplay= true class="video-js" preload="auto" controls playsinline>
		    </video>
		<% else %>
		    <video src="<%= video.unique_url %>" style="width:100%" poster= <%= posturl %> class="video-js"  preload="auto" controls playsinline>
		    </video>
		<% end %>
	  <% else %>
        <% if needautoplayvideo %>
		    <video src="<%= video.unique_url %>" style="width:100%" autoplay= true class="video-js"  preload="auto" controls playsinline>
		    </video>
		<% else %>
		    <video src="<%= video.unique_url %>" style="width:100%" class="video-js"  preload="auto" controls playsinline>
		    </video>
		<% end %>
	  <% end %>

app/views/common/_votebar_battle.html.erb
  <% battle = local_assigns[:battle] %>

  <% if battle %>
  <div class="row">
    <div class="col-sm-2 col-xs-2" style="margin-top: 10px;">
        <%= render :partial => "common/leftvotebutton", locals: {battle: battle}%>     
    </div>
    <div class = "col-sm-8 col-xs-8">
        <%= render :partial => "common/votebar", locals: {battle: battle}%>
    </div>
    <div class="col-sm-2 col-xs-2" style="text-align:right; margin-top: 10px;">
        <%= render :partial => "common/rightvotebutton", locals: {battle: battle}%>     
    </div>
    </div>
  <% end %>

app/views/common/_votebar_battle_challenge.html.erb
  <% battle = local_assigns[:battle] %>

    <%= render :partial => "common/votebar_battle", locals: {battle: battle}%>
      <div class="row">
          <% if is_my_battle(battle) %>
          <% else %>
               <% if left_is_voted(battle) %>
                  <div class="col-sm-12 col-xs-12 text-center">
                    <%= link_to("怼右边", myasset_video_challenge_url(battle.right_video), :class => "btn btn-default challenge_right") %>
                  </div>
               <% elsif right_is_voted(battle) %>
                  <div class="col-sm-12 col-xs-12 text-center">
                    <%= link_to("怼左边", myasset_video_challenge_url(battle.left_video), :class => "btn btn-default challenge_left") %>
                  </div>  
               <% end %>
           <% end %>
      </div>